In [1]:
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC



In [14]:

#open the csv files
csv_path_fake = os.path.join( './', 'News_dataset', 'Fake.csv')
csv_path_true = os.path.join( './', 'News_dataset', 'True.csv')

df_fake = pd.read_csv(csv_path_fake)
df_true = pd.read_csv(csv_path_true)


In [15]:
#add a label column to the dataframes
df_fake['label'] = 'fake'
df_true['label'] = 'true'

df = pd.concat([df_fake, df_true], ignore_index=True)

#save the dataframe to a csv file
df.to_csv('news.csv', index=False)

In [7]:
# open the csv file with pandas

df = pd.read_csv('news.csv')

#split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['label'], test_size=0.1, random_state=7)

#initialize a TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.9)

#fit and transform train set, transform test set
tfidf_train = tfidf_vectorizer.fit_transform(X_train)
tfidf_test = tfidf_vectorizer.transform(X_test)

In [18]:




#initialize a PassiveAggressiveClassifier
pac = PassiveAggressiveClassifier(max_iter=50)
pac.fit(tfidf_train, y_train)

#predict on the test set and calculate accuracy
y_pred = pac.predict(tfidf_test)
score = accuracy_score(y_test, y_pred)
print(f'Accuracy: {round(score*100,2)}%')

#build confusion matrix
confusion_matrix(y_test, y_pred, labels=['fake', 'true'])


Accuracy: 99.38%


array([[2335,   11],
       [  17, 2127]])

In [19]:
#with logistic regression
logreg = LogisticRegression()
logreg.fit(tfidf_train, y_train)
y_pred = logreg.predict(tfidf_test)
score = accuracy_score(y_test, y_pred)
print(f'Accuracy: {round(score*100,2)}%')

#build confusion matrix
confusion_matrix(y_test, y_pred, labels=['fake', 'true'])

Accuracy: 98.66%


array([[2317,   29],
       [  31, 2113]])

In [20]:
#with multinomial naive bayes

nb = MultinomialNB()
nb.fit(tfidf_train, y_train)
y_pred = nb.predict(tfidf_test)
score = accuracy_score(y_test, y_pred)
print(f'Accuracy: {round(score*100,2)}%')

#build confusion matrix
confusion_matrix(y_test, y_pred, labels=['fake', 'true'])

Accuracy: 93.96%


array([[2221,  125],
       [ 146, 1998]])

In [22]:
# with a random forest classifier

rf = RandomForestClassifier()
rf.fit(tfidf_train, y_train)
y_pred = rf.predict(tfidf_test)
score = accuracy_score(y_test, y_pred)
print(f'Accuracy: {round(score*100,2)}%')

#build confusion matrix
confusion_matrix(y_test, y_pred, labels=['fake', 'true'])

Accuracy: 98.89%


array([[2324,   22],
       [  28, 2116]])

In [9]:
# with a support vector machine

svc = LinearSVC(random_state=0, dual='auto')
svc.fit(tfidf_train, y_train)
y_pred = svc.predict(tfidf_test)
score = accuracy_score(y_test, y_pred)
print(f'Accuracy: {round(score*100,2)}%')

#build confusion matrix
confusion_matrix(y_test, y_pred, labels=['fake', 'true'])

Accuracy: 99.47%


array([[2337,    9],
       [  15, 2129]])

In [9]:
# using Liar dataset

csv_path_liar_train = os.path.join( './', 'liar_dataset', 'train.tsv')
csv_path_liar_test = os.path.join( './', 'liar_dataset', 'test.tsv')

df_liar_train = pd.read_csv(csv_path_liar_train, sep='\t', header=None)
df_liar_test = pd.read_csv(csv_path_liar_test, sep='\t', header=None)

df_liar_train.columns = ['id', 'label', 'statement', 'subject', 'speaker', 'job', 'state', 'party', 'barely_true', 'false', 'half_true', 'mostly_true', 'pants_on_fire', 'context']
df_liar_test.columns = ['id', 'label', 'statement', 'subject', 'speaker', 'job', 'state', 'party', 'barely_true', 'false', 'half_true', 'mostly_true', 'pants_on_fire', 'context']

In [11]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.9)

#fit and transform train set, transform test set
tfidf_train = tfidf_vectorizer.fit_transform(df_liar_train['statement'])
tfidf_test = tfidf_vectorizer.transform(df_liar_test['statement'])

#initialize a PassiveAggressiveClassifier
pac = PassiveAggressiveClassifier(max_iter=1000)
pac.fit(tfidf_train, df_liar_train['label'])

#predict on the test set and calculate accuracy
y_pred = pac.predict(tfidf_test)
score = accuracy_score(df_liar_test['label'], y_pred)
print(f'Accuracy: {round(score*100,2)}%')

#build confusion matrix
confusion_matrix(df_liar_test['label'], y_pred, labels=['true', 'mostly-true', 'half-true', 'barely-true', 'false', 'pants-fire'])


Accuracy: 22.81%


array([[43, 38, 49, 22, 47,  9],
       [49, 51, 52, 36, 38, 15],
       [50, 58, 59, 39, 37, 22],
       [36, 43, 31, 40, 41, 21],
       [38, 49, 38, 36, 74, 14],
       [14, 11, 13, 15, 17, 22]])

In [13]:
# with logistic regression
logreg = LogisticRegression(max_iter=1000)
logreg.fit(tfidf_train, df_liar_train['label'])
y_pred = logreg.predict(tfidf_test)
score = accuracy_score(df_liar_test['label'], y_pred)
print(f'Accuracy: {round(score*100,2)}%')

#build confusion matrix
confusion_matrix(df_liar_test['label'], y_pred, labels=['true', 'mostly-true', 'half-true', 'barely-true', 'false', 'pants-fire'])


Accuracy: 25.02%


array([[47, 50, 46, 13, 50,  2],
       [50, 56, 65, 25, 44,  1],
       [28, 65, 84, 37, 47,  4],
       [22, 37, 53, 44, 55,  1],
       [29, 50, 57, 26, 84,  3],
       [ 7, 14, 25, 13, 31,  2]])

In [14]:
# with multinomial naive bayes

nb = MultinomialNB()
nb.fit(tfidf_train, df_liar_train['label'])
y_pred = nb.predict(tfidf_test)
score = accuracy_score(df_liar_test['label'], y_pred)
print(f'Accuracy: {round(score*100,2)}%')

#build confusion matrix
confusion_matrix(df_liar_test['label'], y_pred, labels=['true', 'mostly-true', 'half-true', 'barely-true', 'false', 'pants-fire'])

Accuracy: 23.76%


array([[ 15,  59,  79,   3,  52,   0],
       [ 14,  65, 115,   7,  40,   0],
       [  7,  68, 126,  17,  47,   0],
       [  8,  37,  93,  18,  56,   0],
       [ 12,  51,  99,  10,  77,   0],
       [  2,  18,  36,   7,  29,   0]])

In [15]:
# with a random forest classifier

rf = RandomForestClassifier()
rf.fit(tfidf_train, df_liar_train['label'])
y_pred = rf.predict(tfidf_test)
score = accuracy_score(df_liar_test['label'], y_pred)
print(f'Accuracy: {round(score*100,2)}%')

#build confusion matrix
confusion_matrix(df_liar_test['label'], y_pred, labels=['true', 'mostly-true', 'half-true', 'barely-true', 'false', 'pants-fire'])

Accuracy: 24.63%


array([[ 23,  61,  40,  15,  67,   2],
       [ 35,  76,  48,  26,  55,   1],
       [ 18,  76,  70,  21,  77,   3],
       [ 15,  46,  42,  30,  76,   3],
       [ 20,  43,  48,  26, 109,   3],
       [ 10,  10,  14,  13,  41,   4]])

In [16]:
# with a support vector machine

svc = LinearSVC(random_state=0, dual='auto')
svc.fit(tfidf_train, df_liar_train['label'])
y_pred = svc.predict(tfidf_test)
score = accuracy_score(df_liar_test['label'], y_pred)
print(f'Accuracy: {round(score*100,2)}%')

#build confusion matrix
confusion_matrix(df_liar_test['label'], y_pred, labels=['true', 'mostly-true', 'half-true', 'barely-true', 'false', 'pants-fire'])

Accuracy: 24.55%


array([[53, 44, 51, 15, 38,  7],
       [52, 49, 53, 36, 42,  9],
       [31, 68, 67, 51, 38, 10],
       [24, 31, 47, 56, 44, 10],
       [35, 47, 46, 30, 76, 15],
       [10, 12, 21, 17, 22, 10]])

In [20]:
# using deep learning torch

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader


class NewsDataset(Dataset):
    def __init__(self, csv_file, transform=None):
        self.data = pd.read_csv(csv_file)
        self.transform = transform

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()

        text = self.data.iloc[idx, 1]
        label = self.data.iloc[idx, 2]

        if self.transform:
            text = self.transform(text)

        return text, label
    
class ToTensor(object):
    """Convert ndarrays in sample to Tensors."""

    def __call__(self, text):
        return torch.from_numpy(text).float()
    
class TextCNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim, n_filters, filter_sizes, output_dim, dropout):
        super().__init__()
        
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        
        self.convs = nn.ModuleList([
                                    nn.Conv2d(in_channels = 1, 
                                              out_channels = n_filters, 
                                              kernel_size = (fs, embedding_dim)) 
                                    for fs in filter_sizes
                                    ])
        
        self.fc = nn.Linear(len(filter_sizes) * n_filters, output_dim)
        
        self.dropout = nn.Dropout(dropout)
        
    def forward(self, text):
        
        #text = [sent len, batch size]
        
        text = text.permute(1, 0)
                
        #text = [batch size, sent len]
        
        embedded = self.embedding(text)
                
        #embedded = [batch size, sent len, emb dim]
        
        embedded = embedded.unsqueeze(1)
        
        #embedded = [batch size, 1, sent len, emb dim]
        
        conved = [F.relu(conv(embedded)).squeeze(3) for conv in self.convs]
            
        #conv_n = [batch size, n_filters, sent len - filter_sizes[n] + 1]
                
        pooled = [F.max_pool1d(conv, conv.shape[2]).squeeze(2) for conv in conved]
        
        #pooled_n = [batch size, n_filters]
        
        cat = self.dropout(torch.cat(pooled, dim = 1))
        
        #cat = [batch size, n_filters * len(filter_sizes)]
            
        return self.fc(cat)
    
def binary_accuracy(preds, y):
    """
    Returns accuracy per batch, i.e. if you get 8/10 right, this returns 0.8, NOT 8
    """

    #round predictions to the closest integer
    rounded_preds = torch.round(torch.sigmoid(preds))
    correct = (rounded_preds == y).float() 
    acc = correct.sum()/len(correct)
    return acc

def train(model, iterator, optimizer, criterion):
        
        epoch_loss = 0
        epoch_acc = 0
        
        model.train()
        
        for text, labels in iterator:
            
            optimizer.zero_grad()
            
            predictions = model(text).squeeze(1)
            
            loss = criterion(predictions, labels)
            
            acc = binary_accuracy(predictions, labels)
            
            loss.backward()
            
            optimizer.step()
            
            epoch_loss += loss.item()
            epoch_acc += acc.item()
            
        return epoch_loss / len(iterator), epoch_acc / len(iterator)


def evaluate(model, iterator, criterion):
    epoch_loss = 0
    epoch_acc = 0
    
    model.eval()
    
    with torch.no_grad():
    
        for text, labels in iterator:

            predictions = model(text).squeeze(1)
            
            loss = criterion(predictions, labels)
            
            acc = binary_accuracy(predictions, labels)

            epoch_loss += loss.item()
            epoch_acc += acc.item()
        
    return epoch_loss / len(iterator), epoch_acc / len(iterator)


#set hyperparameters
size_of_vocab = len(tfidf_vectorizer.vocabulary_)
embedding_dim = 100
n_filters = 100
filter_sizes = [3,4,5]
output_dim = 1
dropout = 0.5
batch_size = 64

#instantiate the model
model = TextCNN(size_of_vocab, embedding_dim, n_filters, filter_sizes, output_dim, dropout)

#load the pre-trained embeddings
pretrained_embeddings = tfidf_vectorizer.vocabulary_
model.embedding.weight.data.copy_(pretrained_embeddings)

#initialize the optimizer and criterion
optimizer = optim.Adam(model.parameters(), lr=0.0001)
criterion = nn.BCEWithLogitsLoss()

#split the data into train and test sets using test.tsv and train.tsv
train_dataset = NewsDataset(csv_file='./train.tsv', transform=ToTensor())
test_dataset = NewsDataset(csv_file='./test.tsv', transform=ToTensor())

#split the train dataset into train and validation sets
train_data, valid_data = torch.utils.data.random_split(train_dataset, [len(train_dataset)-1000, 1000])

#initialize the dataloaders
train_iterator = DataLoader(train_data, shuffle=True, batch_size=batch_size)
valid_iterator = DataLoader(valid_data, batch_size=batch_size)
test_iterator = DataLoader(test_dataset, batch_size=batch_size)

#train the model
N_EPOCHS = 5

best_valid_loss = float('inf')

for epoch in range(N_EPOCHS):
    
        train_loss, train_acc = train(model, train_iterator, optimizer, criterion)
        valid_loss, valid_acc = evaluate(model, valid_iterator, criterion)
        
        if valid_loss < best_valid_loss:
            best_valid_loss = valid_loss
            torch.save(model.state_dict(), 'tut5-model.pt')
        
        print(f'Epoch: {epoch+1:02}')
        print(f'\tTrain Loss: {train_loss:.3f} | Train Acc: {train_acc*100:.2f}%')
        print(f'\t Val. Loss: {valid_loss:.3f} |  Val. Acc: {valid_acc*100:.2f}%')

#test the model
model.load_state_dict(torch.load('tut5-model.pt'))

test_loss, test_acc = evaluate(model, test_iterator, criterion)

print(f'Test Loss: {test_loss:.3f} | Test Acc: {test_acc*100:.2f}%')









ModuleNotFoundError: No module named 'torch'